"""empty message

Revision ID: 22fbf3aa2a03
Revises: 2cfd3ae225d3
Create Date: 2023-10-22 01:11:33.548169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22fbf3aa2a03'
down_revision = '2cfd3ae225d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expression', sa.String(length=100), nullable=True),
    sa.Column('result', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('calculation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('expression', sa.VARCHAR(length=100), nullable=True),
    sa.Column('result', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('calculator')
    # ### end Alembic commands ###
